// Student list shared by StudentPicker and GroupMaker
const STUDENT_LISTS = {
    "Sugar Gliders": [
        "Hallie",
        "Nika",
        "Charlie",
        "Zion",
        "Shehan",
        "Ollie",
        "Aiden",
        "Willow",
        "Gabriella",
        "Parsia",
        "Audrey",
        "Kiara",
        "Louis",
        "Ellie",
        "Archie",
        "Marco",
        "Andy",
        "Madeline",
        "Leo",
        "Takumi",
        "Evran",
        "Alicia",
        "Jim",
        "Sapphy",
    ],
    LLLL: [
        "Willow",
        "Gabriella",
        "Hallie",
        "Nika",
        "Charlie",
        "Zion",
        "Aiden",
        "Oliver",
        "Evelyn",
        "Amelia",
        "Nadine",
        "Kiki",
        "Kaja",
        "Alexander",
        "Samuel",
        "Timur",
        "Adam",
        "Ryker",
        "Edward",
        "Shehan",
    ],
};

export default STUDENT_LISTS;
